# Generated by Django 3.1 on 2020-08-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0003_auto_20200825_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_model',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
