# Generated by Django 3.1 on 2020-08-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0004_auto_20200825_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_model',
            name='creade_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articles_model',
            name='published_date',
            field=models.DateField(),
        ),
    ]
