# Generated by Django 3.1 on 2020-08-25 16:13

import Articles_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0005_auto_20200825_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_model',
            name='image',
            field=models.ImageField(default='', upload_to=Articles_app.models.image_upload),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles_model',
            name='article_type',
            field=models.CharField(choices=[('PERSONAL ACTIVITIES', 'PERSONAL ACTIVITIES'), ('PROJECTS', 'PROJECTS'), ('vvs', 'المشاريع '), ('BLOG', 'BLOG'), ('EDUCATION', 'EDUCATION')], max_length=150),
        ),
        migrations.AlterField(
            model_name='articles_model',
            name='intro',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='articles_model',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
