# Generated by Django 3.1 on 2020-08-27 12:30


from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0006_auto_20200825_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_model',
            name='main',
            field=models.CharField(max_length=25),
        ),
    ]
