# Generated by Django 3.1 on 2020-08-26 13:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0006_auto_20200825_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_model',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AlterField(
            model_name='articles_model',
            name='main',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
