# Generated by Django 3.1 on 2020-08-27 13:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0007_auto_20200827_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_model',
            name='text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles_model',
            name='main',
            field=models.CharField(max_length=60),
        ),
    ]
