# Generated by Django 3.1 on 2020-08-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0008_auto_20200827_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles_model',
            name='main',
        ),
    ]
