# Generated by Django 3.1 on 2020-08-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0007_auto_20200826_1327'),
        ('Articles_app', '0010_comments'),
    ]

    operations = [
    ]
