# Generated by Django 3.1 on 2020-08-31 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0012_auto_20200829_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles_app.comments', verbose_name='Comments_comment')),
            ],
        ),
    ]
