# Generated by Django 3.1 on 2020-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0013_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
    ]
