# Generated by Django 3.1 on 2020-09-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_app', '0014_comments_aproved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments_comment',
        ),
    ]
